<?php
/**
 * CollectionDataTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  I2I\ServiceApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * i2i Service API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.35
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace I2I\ServiceApi;

/**
 * CollectionDataTest Class Doc Comment
 *
 * @category    Class
 * @description CollectionData
 * @package     I2I\ServiceApi
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CollectionDataTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CollectionData"
     */
    public function testCollectionData()
    {
    }

    /**
     * Test attribute "uid"
     */
    public function testPropertyUid()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "desc"
     */
    public function testPropertyDesc()
    {
    }

    /**
     * Test attribute "owner"
     */
    public function testPropertyOwner()
    {
    }

    /**
     * Test attribute "group"
     */
    public function testPropertyGroup()
    {
    }

    /**
     * Test attribute "priv"
     */
    public function testPropertyPriv()
    {
    }

    /**
     * Test attribute "gowner"
     */
    public function testPropertyGowner()
    {
    }

    /**
     * Test attribute "nowner"
     */
    public function testPropertyNowner()
    {
    }

    /**
     * Test attribute "list_style"
     */
    public function testPropertyListStyle()
    {
    }
}
